name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: [self-hosted, cross-compile]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get LibOQS latest commit hash
        id: liboqs-hash
        run: |
          LIBOQS_REPO="https://github.com/open-quantum-safe/liboqs.git"
          LIBOQS_BRANCH="main"
          LIBOQS_HASH=$(git ls-remote $LIBOQS_REPO refs/heads/$LIBOQS_BRANCH | cut -f1)
          echo "hash=$LIBOQS_HASH" >> $GITHUB_OUTPUT
          echo "LibOQS latest commit: $LIBOQS_HASH"

      - name: Cache WASM modules
        id: cache-wasm
        uses: actions/cache@v4
        with:
          path: dist/
          key: wasm-modules-${{ steps.liboqs-hash.outputs.hash }}-${{ hashFiles('build.sh', 'algorithms.json') }}
          restore-keys: |
            wasm-modules-${{ steps.liboqs-hash.outputs.hash }}-
            wasm-modules-

      - name: Install dependencies
        run: bun install

      - name: Build WASM modules
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        run: bun run build
        env:
          PARALLEL_JOBS: 8

      - name: Save WASM modules to cache
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: dist/
          key: wasm-modules-${{ steps.liboqs-hash.outputs.hash }}-${{ hashFiles('build.sh', 'algorithms.json') }}

      - name: Verify WASM modules completeness
        run: |
          set -euo pipefail
          # 97 algorithms total (32 KEM + 65 SIG)
          expected_count=97
          actual_count=$(find dist/ -name "*.min.js" -type f | wc -l)

          echo "Expected: $expected_count WASM modules"
          echo "Actual: $actual_count WASM modules"

          if [ "$actual_count" -ne "$expected_count" ]; then
            echo "::error::WASM module count mismatch. Expected $expected_count, got $actual_count"
            find dist/ -name "*.min.js" -type f | sort
            exit 1
          fi

          echo "✅ All $expected_count WASM modules verified"

      - name: Run tests
        run: bun run test

      - name: Generate documentation
        run: bun run docs

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
          retention-days: 7

  publish-npm:
    needs: build-and-test
    runs-on: [self-hosted, cross-compile]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_API_KEY }}" >> ~/.npmrc

      - name: Publish to npm (latest)
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm publish --access public

      - name: Publish to npm (dev)
        if: github.ref == 'refs/heads/main'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          npm version "${VERSION}-dev.$(date +%s)" --no-git-tag-version
          npm publish --tag dev --access public

  deploy-docs:
    needs: build-and-test
    runs-on: [self-hosted, cross-compile]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: docs
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Download documentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs-temp/

      - name: Prepare docs branch
        run: |
          # Remove everything except .git
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'docs-temp' -exec rm -rf {} +

          # Move docs to root
          mv docs-temp docs

      - name: Commit and push documentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update documentation from ${{ github.sha }}"
            git push origin docs
          fi
